refine language
apostrophecms/apostrophe-redirects pull request #26
Opened 2021-02-10 19:53 UTC by boutell

2021-02-10 23:04 UTC, abea requested changes

2021-02-10 23:04 UTC, abea commented on README.md
> +By default a redirect includes any query string (the `?` and whatever follows it, up to but not including any `#`) on incoming requests when matching for redirection. You can toggle the "ignore query
> "ignore query string when matching."

We should either leave as capitalized to match the UI or remove the period to suggest the sentence as a quotation.

2021-02-10 23:05 UTC, abea commented
I don't think the other PRs bumped the version number or updated the changelog. Might as well do that here.

2021-02-11 13:47 UTC, boutell commented
I removed the period. The changelog update and the version bump are already in place.

2021-02-11 16:02 UTC, abea approved these changes

2021-02-12 14:26 UTC, merged